Importar librería Numpy


In [ ]:
import numpy as np

In [ ]:
a = np.array([5,4,3])
print(a)
print(type(a))   # Arreglo unidimensional, vector?
print(a[1])
a.shape  # Muestra la forma del arreglo, (3,) = tiene tres elementos

[5 4 3]
<class 'numpy.ndarray'>
4


(3,)

In [ ]:
b = np.array([[4,5,3],[6,2,3]])
b

array([[4, 5, 3],
       [6, 2, 3]])

In [ ]:
b.shape  # (2,3) 2 filas y 3 columnas

(2, 3)

In [ ]:
b[1,1]  # elemento de la posición (fila 1, columna 1)

2

In [ ]:
matriz = np.zeros((3,4)) #crear matriz de ceros ( 3 filas, 4 columnas)
matriz

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
matriz = np.zeros((3,4,5)) # matriz de ceros (3 matrices, 4 filas, 5 columnas)
matriz

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [ ]:
matriz7 = np.full((3,4),7) # np.full crea la matriz que uno quiera
matriz7

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [ ]:
matriz_random = np.random.random((10,10)) # Matriz de datos aleatorios
matriz_random

array([[0.28066154, 0.26182861, 0.58375625, 0.33598117, 0.59815825,
        0.13271036, 0.75548707, 0.65793179, 0.20915166, 0.75484011],
       [0.15083028, 0.04241082, 0.55793159, 0.21578784, 0.12684995,
        0.79742494, 0.51932717, 0.49202726, 0.92232276, 0.27523951],
       [0.57637282, 0.3421617 , 0.00970275, 0.99343257, 0.61020031,
        0.14848631, 0.6615058 , 0.41744721, 0.16765234, 0.47464303],
       [0.14191607, 0.8928738 , 0.96144454, 0.19533198, 0.41635085,
        0.65351691, 0.11429545, 0.48151182, 0.04097985, 0.04753523],
       [0.31800005, 0.61330644, 0.96590736, 0.01796186, 0.48609427,
        0.12445085, 0.46647844, 0.61715875, 0.12947289, 0.20896988],
       [0.09997785, 0.67601617, 0.44758808, 0.29795993, 0.07239463,
        0.5089599 , 0.50709857, 0.32996954, 0.13379981, 0.85864432],
       [0.81505814, 0.46724613, 0.83952701, 0.55910963, 0.30117252,
        0.91988633, 0.50754707, 0.02660486, 0.98115049, 0.06491035],
       [0.70956782, 0.51742974, 0.6955010

In [ ]:
matriz2 = np.array([[4,5,8,9], [6,89,70,45], [200, 677, 900, 456]])
x
y = x[0:2,1:3]
y

array([[ 5,  8],
       [89, 70]])

In [ ]:
z = x[:2,:3]  #??
z

array([[ 4,  5,  8],
       [ 6, 89, 70]])

#**MATRICES**

In [ ]:
from numpy import random as r

In [ ]:
print(r.choice(['Andres', 'Juan', 'Pedro', 'Mateo'], size= r.choice([1,3],p=[0.1,0.9]), p=[0.5,0.2,0.2,0.1], replace=False))

['Juan' 'Pedro' 'Andres']


In [ ]:
a = np.array([34,25,7])
a

array([34, 25,  7])